### ISSUE TITLE
Apply template to packages and gather feedback

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/BestieTemplate.jl#106]
Choose a package, apply the template, see the result, gather feedback.

Some possible questions:

- Report the package usage experience
- How clear is the documentation?
- Any errors?
- How easy to solve are the conflicts?
- How much does `pre-commit run -a` changes the existing package structure?
- How much does the workflows differ
- How much are we contributing to the package

> [!WARNING]
>
> Don't create pull request adding the changes to the package without discussing it in an issue with the package owners first.

**Comment by luisaforozco** [comment]
Hello, I have tried to apply CopierTemplate.jl to one of my projects and I have the following comments: 
The use of CopierTemplate.jl was very straightforward.
- How clear is the documentation?
It would be nice to have an explicit section at Quickstart dedicated to applying the template to an existing project via:
`copier copy https://github.com/abelsiqueira/COPIERTemplate.jl .` 
Currently only working via python.
It would also be nice to mention explicitly that you can add multiple authors separated by `,` and the same for emails.
#147 
- Errors:
The UUID that it fills out is going to be random, not the one of the project. it would be nice if in the docs there is a be careful! message. 
- How easy to solve are the conflicts?
I got conflicts and choose to overwrite the files, but only Y/n choice.
```julia
 Overwrite docs/make.jl? [Y/n]
```
It would be nice if you could see the diff, maybe resolve the conflicts like in git?
- Other notes:
I had an Apache 2.0 license, I selected the same, and it did not overwrote them. (this is nice behaviour!)

**Comment by abelsiqueira** [comment]
Created https://github.com/TulipaEnergy/TulipaIO.jl/pull/50 and https://github.com/TulipaEnergy/TulipaIO.jl/pull/51, which are part of the NextGenOpt project.

- How easy to solve are the conflicts?

README.md and docs/src/index.md are mostly lost in the first application or the first change in all contributors.

- How much does pre-commit run -a changes the existing package structure?

In this case, the Julia codes were using 4 spaces for indentation and most other files were using 2, so it made several changes.
