### ISSUE TITLE
Find early adopters

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/BestieTemplate.jl#267]
### Description

We are looking for early adopters, i.e., packages and their maintainers that want to try some of these best practices.
We gather feedback from these packages, and hopefully help maintaining and developing this package.

We can offer some help applying and maintaining the changes that we are proposing for a few months, at least.

**Comment by abelsiqueira** [comment]
@odow @gdalle @giordano @lucaferranti @bvdmitri @milescranmer @tmigot @dpo @amontoison
Maybe this is of interest to you?

**Comment by lucaferranti** [comment]
Looks very cool! I could try how this feels applying to FuzzyLogic.jl 

@FabsOliveira could be interested too

**Comment by abelsiqueira** [comment]
That would be great, thanks!

**Comment by FabsOliveira** [comment]
@EetuReijonen, could this be something to consider for [Gogeta.jl](https://github.com/gamma-opt/Gogeta.jl)?

**Comment by tmigot** [comment]
Hi @abelsiqueira ! That looks really great, looking forward to use it in [JSOSuite.jl](https://github.com/JuliaSmoothOptimizers/JSOSuite.jl) and try to make a new package with it.

**Comment by abelsiqueira** [comment]
Thanks for all the help y'all. I am closing this for internal control, but everyone is still more than welcome to join and ask for guidance.
