### ISSUE TITLE
Renaming a package

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/BestieTemplate.jl#271]
### Description

Let's say I want to rename a package. If I run `update` and change the name, will it be enough?
Should we add a function `rename` to help?

**Comment by fdiblen** [comment]
asciinema demo still uses `COPIERtemplate` instead of BestieTemplate.
See: https://asciinema.org/a/611189

**Comment by abelsiqueira** [comment]
Renaming is a rare occurrence, so I will close this and wait for someone with the actual issue to reopen it.
