### ISSUE TITLE
The link to documentation is wrong

### ISSUE THREAD

**Issue by Eben60** [abelsiqueira/BestieTemplate.jl#291]
### Description

[abelsiqueira.com/COPIERTemplate.jl/](http://abelsiqueira.com/COPIERTemplate.jl/) is probably obsolete

**Comment by abelsiqueira** [comment]
Hi @Eben60, I found a link where that was wrong in the repo description, thanks for the issue.
Was there somewhere else?

**Comment by Eben60** [comment]
That was it, thanks for correcting ☺
