### ISSUE TITLE
Shell commands after creating package could be all copy pastable

### ISSUE THREAD

**Issue by suvayu** [abelsiqueira/BestieTemplate.jl#309]
### Description

After creating a package, Bestie prints a set of shell commands to initialise a git repository.  These commands are all copy pastable, except the initial `cd`.

- `cd <path>` -> `cd "path/MyPackage.jl"`

### Motivation

Reduce friction

### Target audience

Beginner user

**Comment by abelsiqueira** [comment]
This was side-fixed in #379.
