### ISSUE TITLE
[Bug] Workflow TestGeneratedPkg is failing

### ISSUE THREAD

**Issue by abelsiqueira** [abelsiqueira/BestieTemplate.jl#322]
### Description

https://github.com/abelsiqueira/BestieTemplate.jl/actions/runs/9791208002

### Package Version

NA

### Julia Version

NA

### Reproduction steps

https://github.com/abelsiqueira/BestieTemplate.jl/actions/runs/9791208002

**Comment by suvayu** [comment]
The failure is strange since I was expecting failure would print out the names of the files that are missing (output of `| grep missing`).  Maybe some other kind of error is happening?

**Comment by suvayu** [comment]
Found it! It's because the shell is invoked as `bash -e`, which always fails whenever a pipe fails; see [(bash) The Set Builtin](https://www.gnu.org/software/bash/manual/bash.html#The-Set-Builtin)!  We need a different way to detect this :thinking:
