### ISSUE TITLE
Less opinionated and simpler minimal config

### ISSUE THREAD

**Issue by gdalle** [abelsiqueira/BestieTemplate.jl#355]
### Description

Edit: Moved the list here so it works

- [x] #357
- [x] #358

Here are a few changes I'd like to see in the default config before we (re-)generate FixMe.jl:

For docs:
- The [`nice_name`](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/docs/make.jl#L8-L14) is not needed because Documenter.jl will automatically pull the title of the markdown file (and not the file name) if you put file names instead of pairs in the `pages` argument to `makedocs`
- Remove [`doctest=true`](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/docs/make.jl#L18) because it is the default
- Remove [`linkcheck=false`](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/docs/make.jl#L19) because Documenter.jl's linkcheck also checks internal references
- Remove [`repo=...`](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/docs/make.jl#L21) because Documenter.jl [figures it out](https://github.com/JuliaCI/PkgTemplates.jl/pull/450) itself from a GitHub repo
- Remove [`prettyurls=true`](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/docs/make.jl#L24) because it is the default
- Remove [`assets=...`](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/docs/make.jl#L26) to have default styling
- Don't activate [`push_preview`](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/docs/make.jl#L37), or add a CI workflow to [clean up the previews after closing](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/docs/make.jl#L37)

For the rest:

- Leave `JuliaFormatter.toml` empty or pick a generic style guide (`style="blue"` is a good choice) instead of individual custom options
- Leave `.editorconfig` empty
- Isn't `CODECOV_TOKEN` supposed to be [in uppercase](https://github.com/abelsiqueira/BestieMinimum.jl/blob/f8f98d3076f1c085904d7668e239d96e9dce068e/.github/workflows/ReusableTest.yml#L52)?

Ping @abelsiqueira and @CasBex

**Comment by abelsiqueira** [comment]
Listing so it becomes issues:

- [ ] Clean up `docs/make.jl`
- [ ] #63 
- [ ] Change JuliaFormatter style to `style="blue"`.

Cleaning the previews is already an issue, just linked it. The rest of the docs comments seem good. Let's see how they render with the changes.

Why the `.editorconfig` empty? It's mostly a no-op. Is there a specific line that you want removed?

`CODECOV_TOKEN` is uppercase, but ReusableWorkflows uses the passed secret from `Test` and `TestOnPRs` (it's uppercase there. ReusableWorkflows can't use CODECOV_TOKEN directly. I named it as an argument (snake_case).

@CasBex, let me know if you want to work on any of these issues.

**Comment by CasBex** [comment]
I'm not too familiar with all the CI stuff so I'm not really the right person for this I think.

**Comment by abelsiqueira** [comment]
No prob, I'll update it.

**Comment by abelsiqueira** [comment]
Some comments, discussed with @gdalle:

- I left the `repo` keyword because it's used in the tests and needed if you don't have a GH repo yet.
- I left some basic formatting in JuliaFormatter, but no strong opinions. editorconfig is kept for the same reason.

I am releasing 0.9.0 right now with these changes.

**Comment by abelsiqueira** [comment]
@allcontributors please add @gdalle for ideas

**Comment by abelsiqueira** [comment]
Some of these were discussed in person at the JuliaCon 2024 Hackathon and some were implemented. I'll close, but feel free to open with comments on what it missing.
