### ISSUE TITLE
make email optional

### ISSUE THREAD

**Issue by lucaferranti** [abelsiqueira/BestieTemplate.jl#356]
### Description

Currently, when BestieTemplates.jl asks for email, it cannot be empty. However, users may not want to have their email in the wild in the internet (especially if it's a personal project and cannot use an institutional email). Would be nice to make the email optional

**Comment by abelsiqueira** [comment]
@addcontributors please add @lucaferranti for ideas

**Comment by abelsiqueira** [comment]
@allcontributors please add @lucaferranti for ideas

**Comment by abelsiqueira** [comment]
Fixed by #432.
