### ISSUE TITLE
[Bug] Lots of errors with fresh application in pre-commit

### ISSUE THREAD

**Issue by moble** [abelsiqueira/BestieTemplate.jl#390]
### Description

Running `pre-commit run -a`, as recommended in the docs, produced lots of errors from files that were added by BestieTemplate.  For example, the various `ISSUE_TEMPLATE` files had lines that were too long.  I had to tweak lots of config options, including adding a `.yamllint.yaml` file, to get past the errors.

### Package Version

0.9.1

### Julia Version

1.10.4

### Reproduction steps

I [applied Bestie to an existing package](https://abelsiqueira.com/BestieTemplate.jl/stable/10-full-guide/#existing_package) and ran `pre-commit run -a`.

**Comment by abelsiqueira** [comment]
I've implemented tests to make sure that the pre-commit errors are being fixed with the first execution of pre-commit.
If this is not your experience, feel free to reopen this or open a new issue, but please help me reproduce it.
