### ISSUE TITLE
[Bug] Default indentation level should be 4 spaces

### ISSUE THREAD

**Issue by oxinabox** [abelsiqueira/BestieTemplate.jl#403]
### Description

This is the ubiquitous default throughout the julia ecosystem

This is specified in
 - [JuliaLang contributing guidelines](https://github.com/JuliaLang/julia/blob/master/CONTRIBUTING.md#general-formatting-guidelines-for-julia-code-contributions)
 - [BlueStyle](https://github.com/JuliaDiff/BlueStyle?tab=readme-ov-file#synopsis)
 - JuMP style guide specifies a [`.format` file](https://github.com/jump-dev/JuMP.jl/blob/master/.JuliaFormatter.toml), which just uses the [default of 4](https://github.com/domluna/JuliaFormatter.jl/blob/add49166e7f7c6a7b9b10dd6b7abe0ecb6328c2a/src/options.jl#L4)
 - [YASGuide](https://github.com/jrevels/YASGuide?tab=readme-ov-file#linealignmentspacing-guidelines)
 - [SciMLStyle](https://github.com/SciML/SciMLStyle?tab=readme-ov-file#high-level-rules)
 
 
 It's not my personal preference.
 But it is much more important to be consistent than anything else when it comes to style.

### Package Version

v0.9.1

### Julia Version

1.10

### Reproduction steps

Create a new folder, 
run `BestieTeimplates.generate`
Observe that it prefills in a default indent of 2.

### Relevant log output

```shell
julia> using BestieTemplate
...
julia> BestieTemplate.generate("./POC_kinetic/")
  Hi, ❤ Bestie ❤ here.
...
  ❤ Good luck filling the questions, and thanks for choosing BestieTemplate ❤

🎤 Package name (without '.jl')
...
🎤 Indentation length (Used in .JuliaFormatter and other configuration files of formatters and linters if y
   2
```
```


### Operating System

Linux

**Comment by abelsiqueira** [comment]
Makes sense, let's change it.
