### ISSUE TITLE
Change CI settings to only require approval for first-time contributors who are new to GitHub

### ISSUE THREAD

**Issue by oxinabox** [abelsiqueira/BestieTemplate.jl#405]
Right now the CI settings are set to **Require approval for first-time contributors**
but that's really annoying, because it means any new contributor will always require intervention from a maintainer to be allowed to run CI.
Which in turn means the guidelines in the PR template saying to leave as a Draft until the Lint and Test workflow jobs are complete can't be followed. Since if left as a draft no maintainer will get a message about it so they will not think to enable the workflow jobs.

If you go to https://github.com/abelsiqueira/BestieTemplate.jl/settings/actions
then down to **Fork pull request workflows from outside collaborators**
you can select: _Require approval for first-time contributors who are new to GitHub_
which is a more relaxed setting meaning established github users have the CI run automatically.
As shown in the screenshot below
![screenshot of menu](https://github.com/user-attachments/assets/41b88f0c-7a6c-4000-8fc6-77e7bb62da09)

**Comment by abelsiqueira** [comment]
Done. Thanks for the tip.
