### ISSUE TITLE
Next steps list: add exit() - exit Julia-repl

### ISSUE THREAD

**Issue by luisaforozco** [abelsiqueira/BestieTemplate.jl#463]
### Description

The user generates or apply BestieTemplate from the julia-repl. The Next steps instructions are very clear, but I found my lazy self typing `cd ./MyPackage.jl` inside the julia-repl.
This issue is to suggest to add as first command: `exit()` to exit the julia-repl.

**Comment by abelsiqueira** [comment]
Thanks for the issue. Makes sense. If you want to do a PR, that would be great
